-- tx_swap table
-- Generated from t16o_db instance

DROP TABLE IF EXISTS ;

CREATE TABLE `tx_swap` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tx_id` bigint NOT NULL COMMENT 'FK to tx.id',
  `ins_index` smallint DEFAULT NULL,
  `outer_ins_index` smallint DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `activity_type` varchar(50) DEFAULT NULL,
  `program_id` bigint unsigned DEFAULT NULL COMMENT 'FK to tx_program - DEX program',
  `outer_program_id` bigint unsigned DEFAULT NULL COMMENT 'FK to tx_program - router program',
  `amm_id` bigint unsigned DEFAULT NULL COMMENT 'FK to tx_pool - pool',
  `account_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - trader account',
  `token_1_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - token 1',
  `token_2_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - token 2',
  `amount_1` bigint unsigned DEFAULT NULL,
  `amount_2` bigint unsigned DEFAULT NULL,
  `decimals_1` tinyint unsigned DEFAULT NULL,
  `decimals_2` tinyint unsigned DEFAULT NULL,
  `token_account_1_1_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token1 source ATA',
  `token_account_1_2_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token1 dest ATA',
  `token_account_2_1_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token2 source ATA',
  `token_account_2_2_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token2 dest ATA',
  `owner_1_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - owner 1 wallet',
  `owner_2_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - owner 2 wallet',
  `fee_amount` bigint unsigned DEFAULT NULL,
  `fee_token_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - fee token',
  `side` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tx` (`tx_id`),
  KEY `idx_amm` (`amm_id`),
  KEY `idx_account` (`account_address_id`),
  KEY `idx_token_1` (`token_1_id`),
  KEY `idx_token_2` (`token_2_id`),
  KEY `idx_tx_ins` (`tx_id`,`ins_index`),
  KEY `tx_swap_ibfk_program` (`program_id`),
  KEY `tx_swap_ibfk_outer_program` (`outer_program_id`),
  KEY `tx_swap_ibfk_ta_1_1` (`token_account_1_1_address_id`),
  KEY `tx_swap_ibfk_ta_1_2` (`token_account_1_2_address_id`),
  KEY `tx_swap_ibfk_ta_2_1` (`token_account_2_1_address_id`),
  KEY `tx_swap_ibfk_ta_2_2` (`token_account_2_2_address_id`),
  KEY `tx_swap_ibfk_owner_1` (`owner_1_address_id`),
  KEY `tx_swap_ibfk_owner_2` (`owner_2_address_id`),
  KEY `tx_swap_ibfk_fee_token` (`fee_token_id`),
  CONSTRAINT `tx_swap_ibfk_account` FOREIGN KEY (`account_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_amm` FOREIGN KEY (`amm_id`) REFERENCES `tx_pool` (`id`),
  CONSTRAINT `tx_swap_ibfk_fee_token` FOREIGN KEY (`fee_token_id`) REFERENCES `tx_token` (`id`),
  CONSTRAINT `tx_swap_ibfk_outer_program` FOREIGN KEY (`outer_program_id`) REFERENCES `tx_program` (`id`),
  CONSTRAINT `tx_swap_ibfk_owner_1` FOREIGN KEY (`owner_1_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_owner_2` FOREIGN KEY (`owner_2_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_program` FOREIGN KEY (`program_id`) REFERENCES `tx_program` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_1_1` FOREIGN KEY (`token_account_1_1_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_1_2` FOREIGN KEY (`token_account_1_2_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_2_1` FOREIGN KEY (`token_account_2_1_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_2_2` FOREIGN KEY (`token_account_2_2_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_token_1` FOREIGN KEY (`token_1_id`) REFERENCES `tx_token` (`id`),
  CONSTRAINT `tx_swap_ibfk_token_2` FOREIGN KEY (`token_2_id`) REFERENCES `tx_token` (`id`),
  CONSTRAINT `tx_swap_ibfk_tx` FOREIGN KEY (`tx_id`) REFERENCES `tx` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=842 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
