-- tx table
-- Main transaction record with aggregated swap summary (normalized)

CREATE TABLE IF NOT EXISTS `tx` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `signature` varchar(88) NOT NULL,
  `block_id` bigint unsigned DEFAULT NULL,
  `block_time` bigint unsigned DEFAULT NULL,
  `block_time_utc` datetime DEFAULT NULL,
  `fee` bigint unsigned DEFAULT NULL,
  `priority_fee` bigint unsigned DEFAULT NULL,
  `signer_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - primary signer',
  `agg_program_id` bigint unsigned DEFAULT NULL COMMENT 'FK to tx_program - aggregator program',
  `agg_account_address_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - trader account',
  `agg_token_in_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - input token',
  `agg_token_out_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - output token',
  `agg_amount_in` bigint unsigned DEFAULT NULL,
  `agg_amount_out` bigint unsigned DEFAULT NULL,
  `agg_decimals_in` tinyint unsigned DEFAULT NULL,
  `agg_decimals_out` tinyint unsigned DEFAULT NULL,
  `agg_fee_amount` bigint unsigned DEFAULT NULL,
  `agg_fee_token_id` bigint DEFAULT NULL COMMENT 'FK to tx_token - fee token',
  `tx_json` json DEFAULT NULL,
  `tx_state` varchar(16)  DEFAULT 'shredded',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_signature` (`signature`),
  KEY `idx_block_time` (`block_time`),
  KEY `idx_signer` (`signer_address_id`),
  KEY `idx_agg_account` (`agg_account_address_id`),
  KEY `idx_agg_token_in` (`agg_token_in_id`),
  KEY `idx_agg_token_out` (`agg_token_out_id`),
  KEY `idx_type_state` (`type_state`),
  CONSTRAINT `tx_ibfk_signer` FOREIGN KEY (`signer_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_ibfk_agg_program` FOREIGN KEY (`agg_program_id`) REFERENCES `tx_program` (`id`),
  CONSTRAINT `tx_ibfk_agg_account` FOREIGN KEY (`agg_account_address_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_ibfk_agg_token_in` FOREIGN KEY (`agg_token_in_id`) REFERENCES `tx_token` (`id`),
  CONSTRAINT `tx_ibfk_agg_token_out` FOREIGN KEY (`agg_token_out_id`) REFERENCES `tx_token` (`id`),
  CONSTRAINT `tx_ibfk_agg_fee_token` FOREIGN KEY (`agg_fee_token_id`) REFERENCES `tx_token` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
