-- tx_swap table
-- Individual swap legs from transactions with normalized FKs

CREATE TABLE IF NOT EXISTS `tx_swap` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tx_id` bigint NOT NULL COMMENT 'FK to tx.id',
  `ins_index` smallint DEFAULT NULL,
  `outer_ins_index` smallint DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `activity_type` varchar(50) DEFAULT NULL,
  `program_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - DEX program',
  `outer_program_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - router program',
  `amm_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - pool address',
  `account_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - trader account',
  `token_1_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token 1 mint',
  `token_2_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token 2 mint',
  `amount_1` bigint unsigned DEFAULT NULL,
  `amount_2` bigint unsigned DEFAULT NULL,
  `decimals_1` tinyint unsigned DEFAULT NULL,
  `decimals_2` tinyint unsigned DEFAULT NULL,
  `token_account_1_1_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token1 source ATA',
  `token_account_1_2_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token1 dest ATA',
  `token_account_2_1_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token2 source ATA',
  `token_account_2_2_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - token2 dest ATA',
  `owner_1_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - owner 1 wallet',
  `owner_2_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - owner 2 wallet',
  `fee_amount` bigint unsigned DEFAULT NULL,
  `fee_token_id` int unsigned DEFAULT NULL COMMENT 'FK to tx_address - fee token mint',
  `side` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tx` (`tx_id`),
  KEY `idx_amm` (`amm_id`),
  KEY `idx_account` (`account_id`),
  KEY `idx_token_1` (`token_1_id`),
  KEY `idx_token_2` (`token_2_id`),
  KEY `idx_tx_ins` (`tx_id`, `ins_index`),
  CONSTRAINT `tx_swap_ibfk_tx` FOREIGN KEY (`tx_id`) REFERENCES `tx` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tx_swap_ibfk_program` FOREIGN KEY (`program_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_outer_program` FOREIGN KEY (`outer_program_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_amm` FOREIGN KEY (`amm_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_account` FOREIGN KEY (`account_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_token_1` FOREIGN KEY (`token_1_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_token_2` FOREIGN KEY (`token_2_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_1_1` FOREIGN KEY (`token_account_1_1_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_1_2` FOREIGN KEY (`token_account_1_2_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_2_1` FOREIGN KEY (`token_account_2_1_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_ta_2_2` FOREIGN KEY (`token_account_2_2_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_owner_1` FOREIGN KEY (`owner_1_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_owner_2` FOREIGN KEY (`owner_2_id`) REFERENCES `tx_address` (`id`),
  CONSTRAINT `tx_swap_ibfk_fee_token` FOREIGN KEY (`fee_token_id`) REFERENCES `tx_address` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
